"""
Data Analyst Agent - Core Graph Definition

This module defines the main agent graph using LangChain Deep Agents.
Compatible with LangGraph server for frontend integration.

Architecture:
- Uses create_deep_agent() for automatic TodoList planning
- FilesystemMiddleware for file operations
- Custom tools: execute_python (sandbox), search_web (Tavily)
"""

import os
from typing import Annotated
from langchain_core.messages import HumanMessage
from langchain_core.tools import tool
from deepagents import create_deep_agent

from ..tools.search import internet_search
from ..tools.code_execution import execute_python_tool


# =============================================================================
# Data Analyst System Prompt (appended to Deep Agents base prompt)
# =============================================================================

DATA_ANALYST_PROMPT = """You are an expert data analyst AI assistant, specialized in:

1. **Exploratory Data Analysis (EDA)**
   - Data cleaning and preprocessing
   - Descriptive statistics
   - Data visualization (histograms, scatter plots, correlation matrices)

2. **Statistical Analysis**
   - Hypothesis testing (t-tests, chi-square, ANOVA)
   - Correlation and regression analysis
   - Time series analysis

3. **Econometric Methods**
   - OLS (Ordinary Least Squares) regression
   - Panel data analysis (Fixed Effects, Random Effects)
   - Difference-in-Differences (DID)
   - Instrumental Variables (IV/2SLS)

4. **Output Formatting**
   - Generate publication-quality LaTeX tables
   - Create clear visualizations
   - Write structured analysis reports

## Custom Tools

1. `execute_python` - Execute Python code in a secure sandbox
   - Pre-installed: pandas, numpy, scipy, statsmodels, matplotlib, seaborn
   - Use for all data analysis and computation tasks
   - Images are automatically captured and returned

2. `search_web` - Search the internet for information
   - Use for finding documentation, examples, or domain knowledge

## Working with Uploaded Data Files

Users can upload data files for analysis. Supported formats:
- **CSV** (.csv) - Use `pd.read_csv()`
- **Excel** (.xlsx, .xls) - Use `pd.read_excel()`
- **Stata** (.dta) - Use `pd.read_stata()`
- **SPSS** (.sav) - Use `pd.read_spss()`
- **Parquet** (.parquet) - Use `pd.read_parquet()`

When files are uploaded, you will see information in the user message like:

```
[Uploaded Data Files]
- sales_data.csv (/home/user/data/20241217_abc123_sales_data.csv)
```

**To load uploaded files**, use the path shown in parentheses:

```python
import pandas as pd

# Load the uploaded file using the exact path provided
df = pd.read_csv('/home/user/data/20241217_abc123_sales_data.csv')
print(df.head())
print(df.info())
```

### Best Practices for Data Files

1. **Always check the file first**: Use `.head()`, `.info()`, `.describe()` before analysis
2. **Handle encoding issues**: For CSV, try `encoding='utf-8'` or `encoding='gbk'` for Chinese data
3. **Handle missing values**: Check with `.isnull().sum()` and handle appropriately
4. **Large files**: Use `nrows=1000` parameter first to preview structure

## Data Analysis Guidelines

1. **Plan before executing**: Use the todo list to break down complex analyses
2. **Show your work**: Display intermediate results and explain reasoning
3. **Handle errors gracefully**: If code fails, analyze the error and retry
4. **Format output nicely**: Use clear formatting for results
5. **Generate LaTeX tables**: For regression results, provide LaTeX formatted tables

## Code Execution Tips

When writing Python code:
- Import all required libraries at the start
- Use meaningful variable names
- Print intermediate results for verification
- Handle potential errors with try/except
- For large outputs, summarize key findings
"""


# =============================================================================
# Tool Definitions
# =============================================================================

@tool
def execute_python(
    code: Annotated[str, "Python code to execute"],
    timeout: Annotated[int, "Timeout in seconds"] = 120,
) -> str:
    """
    Execute Python code in a secure sandbox environment.

    The sandbox has pre-installed data science packages:
    - pandas, numpy, scipy
    - statsmodels (for regression analysis)
    - matplotlib, seaborn (for visualization)

    Returns the execution result including stdout, stderr, and any outputs.
    Images generated by matplotlib are automatically captured.
    """
    result = execute_python_tool(code=code, timeout=timeout)

    if result["success"]:
        output_parts = []

        if result["stdout"]:
            output_parts.append(f"Output:\n{result['stdout']}")

        if result["results"]:
            for r in result["results"]:
                if r["type"] == "text/plain" and r["data"] not in result.get("stdout", ""):
                    output_parts.append(f"Result: {r['data']}")
                elif r["type"] == "text/latex":
                    output_parts.append(f"LaTeX:\n{r['data']}")
                elif r["type"] == "image/png":
                    # Return actual base64 image data for frontend rendering
                    output_parts.append(f"![Figure](data:image/png;base64,{r['data']})")

        return "\n\n".join(output_parts) if output_parts else "Code executed successfully (no output)"
    else:
        error_msg = result.get("error", "Unknown error")
        stderr = result.get("stderr", "")
        return f"Execution failed:\n{error_msg}\n{stderr}"


@tool
def search_web(
    query: Annotated[str, "Search query"],
    max_results: Annotated[int, "Maximum results to return"] = 5,
) -> str:
    """
    Search the internet for information.

    Use this tool to find:
    - Documentation and tutorials
    - Code examples
    - Domain-specific knowledge
    - Recent news and updates
    """
    result = internet_search(query=query, max_results=max_results)

    if "error" in result and result["error"]:
        return f"Search error: {result['error']}"

    if not result.get("results"):
        return "No results found"

    output_parts = []
    for i, item in enumerate(result["results"], 1):
        title = item.get("title", "No title")
        url = item.get("url", "")
        snippet = item.get("content", item.get("snippet", ""))
        output_parts.append(f"{i}. **{title}**\n   URL: {url}\n   {snippet[:200]}...")

    return "\n\n".join(output_parts)


# Custom tools for the data analyst agent
CUSTOM_TOOLS = [execute_python, search_web]


# =============================================================================
# Model Selection
# =============================================================================

def get_model():
    """
    Initialize the language model based on available API keys.

    Priority: DeepSeek > Anthropic > OpenAI
    """
    from langchain.chat_models import init_chat_model

    if os.environ.get("DEEPSEEK_API_KEY"):
        return init_chat_model(
            "deepseek-chat",
            model_provider="deepseek",
            api_key=os.environ.get("DEEPSEEK_API_KEY"),
            # Increase timeout for complex data analysis tasks
            # DeepSeek can be slow, especially with multiple tool calls
            timeout=600,  # 10 minutes
            max_retries=2,
        )
    elif os.environ.get("ANTHROPIC_API_KEY"):
        return init_chat_model(
            "claude-sonnet-4-5-20250929",
            model_provider="anthropic",
            api_key=os.environ.get("ANTHROPIC_API_KEY"),
            base_url=os.environ.get("ANTHROPIC_BASE_URL"),
            timeout=600,  # 10 minutes
            max_retries=2,
        )
    elif os.environ.get("OPENAI_API_KEY"):
        return init_chat_model(
            "gpt-4o",
            model_provider="openai",
            api_key=os.environ.get("OPENAI_API_KEY"),
            timeout=600,  # 10 minutes
            max_retries=2,
        )
    else:
        raise ValueError(
            "No API key found. Set one of: "
            "DEEPSEEK_API_KEY, ANTHROPIC_API_KEY, OPENAI_API_KEY"
        )


# =============================================================================
# Create Deep Agent
# =============================================================================

def build_graph():
    """
    Build the data analyst agent using Deep Agents architecture.

    This provides:
    - TodoListMiddleware: Automatic task planning with write_todos tool
    - FilesystemMiddleware: File operations (ls, read, write, edit, glob, grep)
    - SubAgentMiddleware: Ability to spawn subagents (optional)
    - Custom tools: execute_python, search_web
    """
    return create_deep_agent(
        model=get_model(),
        tools=CUSTOM_TOOLS,
        system_prompt=DATA_ANALYST_PROMPT,
    )


# Export the compiled graph (CompiledStateGraph, compatible with LangGraph Server)
graph = build_graph()


# =============================================================================
# Convenience Functions
# =============================================================================

def invoke(query: str, thread_id: str = "default") -> dict:
    """
    Invoke the agent with a query

    Args:
        query: User's question or request
        thread_id: Thread ID for conversation persistence

    Returns:
        Agent response dict
    """
    config = {"configurable": {"thread_id": thread_id}}
    result = graph.invoke(
        {"messages": [HumanMessage(content=query)]},
        config=config,
    )
    return result


def stream(query: str, thread_id: str = "default"):
    """
    Stream the agent's response

    Args:
        query: User's question or request
        thread_id: Thread ID for conversation persistence

    Yields:
        Streaming events from the agent
    """
    config = {"configurable": {"thread_id": thread_id}}
    for event in graph.stream(
        {"messages": [HumanMessage(content=query)]},
        config=config,
        stream_mode="values",
    ):
        yield event
