export type AppCategory =
  | "productivity"
  | "communication"
  | "development"
  | "crm"
  | "social"
  | "storage"
  | "payment"
  | "other";

export interface AppInfo {
  id: string;
  name: string;
  description: string;
  descriptionKey: string;
  category: AppCategory;
  logo: string;
}

export const appCategories: AppCategory[] = [
  "productivity",
  "communication",
  "development",
  "crm",
  "social",
  "storage",
  "payment",
  "other",
];

export const apps: AppInfo[] = [
  {
    id: "notion",
    name: "Notion",
    description:
      "All-in-one workspace for notes, docs, knowledge bases, and project management",
    descriptionKey: "settings.apps.notion.description",
    category: "productivity",
    logo: "/app-logos/notion.svg",
  },
  {
    id: "google-calendar",
    name: "Google Calendar",
    description: "Schedule management and meeting planning tool",
    descriptionKey: "settings.apps.google_calendar.description",
    category: "productivity",
    logo: "/app-logos/google-calendar.svg",
  },
  {
    id: "trello",
    name: "Trello",
    description: "Visual project management and collaboration tool",
    descriptionKey: "settings.apps.trello.description",
    category: "productivity",
    logo: "/app-logos/trello.svg",
  },
  {
    id: "asana",
    name: "Asana",
    description: "Team project and task management platform",
    descriptionKey: "settings.apps.asana.description",
    category: "productivity",
    logo: "/app-logos/asana.svg",
  },
  {
    id: "slack",
    name: "Slack",
    description: "Team messaging and collaboration platform",
    descriptionKey: "settings.apps.slack.description",
    category: "communication",
    logo: "/app-logos/slack.svg",
  },
  {
    id: "zoom",
    name: "Zoom",
    description: "Video meetings and online collaboration tool",
    descriptionKey: "settings.apps.zoom.description",
    category: "communication",
    logo: "/app-logos/zoom.svg",
  },
  {
    id: "discord",
    name: "Discord",
    description: "Community voice, video, and text chat platform",
    descriptionKey: "settings.apps.discord.description",
    category: "communication",
    logo: "/app-logos/discord.svg",
  },
  {
    id: "teams",
    name: "Microsoft Teams",
    description: "Enterprise collaboration and communication platform",
    descriptionKey: "settings.apps.teams.description",
    category: "communication",
    logo: "/app-logos/teams.svg",
  },
  {
    id: "github",
    name: "GitHub",
    description: "Code hosting and version control platform",
    descriptionKey: "settings.apps.github.description",
    category: "development",
    logo: "/app-logos/github.svg",
  },
  {
    id: "gitlab",
    name: "GitLab",
    description: "DevOps platform for code management and CI/CD",
    descriptionKey: "settings.apps.gitlab.description",
    category: "development",
    logo: "/app-logos/gitlab.svg",
  },
  {
    id: "linear",
    name: "Linear",
    description: "Modern issue tracking and project management tool",
    descriptionKey: "settings.apps.linear.description",
    category: "development",
    logo: "/app-logos/linear.svg",
  },
  {
    id: "jira",
    name: "Jira",
    description: "Agile project management and issue tracking tool",
    descriptionKey: "settings.apps.jira.description",
    category: "development",
    logo: "/app-logos/jira.svg",
  },
  {
    id: "salesforce",
    name: "Salesforce",
    description: "Leading customer relationship management platform",
    descriptionKey: "settings.apps.salesforce.description",
    category: "crm",
    logo: "/app-logos/salesforce.svg",
  },
  {
    id: "hubspot",
    name: "HubSpot",
    description: "Marketing, sales, and customer service platform",
    descriptionKey: "settings.apps.hubspot.description",
    category: "crm",
    logo: "/app-logos/hubspot.svg",
  },
  {
    id: "twitter",
    name: "Twitter / X",
    description: "Social media and real-time information platform",
    descriptionKey: "settings.apps.twitter.description",
    category: "social",
    logo: "/app-logos/twitter.svg",
  },
  {
    id: "linkedin",
    name: "LinkedIn",
    description: "Professional social networking platform",
    descriptionKey: "settings.apps.linkedin.description",
    category: "social",
    logo: "/app-logos/linkedin.svg",
  },
  {
    id: "reddit",
    name: "Reddit",
    description: "Community content sharing and discussion platform",
    descriptionKey: "settings.apps.reddit.description",
    category: "social",
    logo: "/app-logos/reddit.svg",
  },
  {
    id: "google-drive",
    name: "Google Drive",
    description: "Cloud file storage and sharing service",
    descriptionKey: "settings.apps.google_drive.description",
    category: "storage",
    logo: "/app-logos/google-drive.svg",
  },
  {
    id: "dropbox",
    name: "Dropbox",
    description: "File sync and cloud storage service",
    descriptionKey: "settings.apps.dropbox.description",
    category: "storage",
    logo: "/app-logos/dropbox.svg",
  },
  {
    id: "onedrive",
    name: "OneDrive",
    description: "Microsoft cloud storage and file sharing service",
    descriptionKey: "settings.apps.onedrive.description",
    category: "storage",
    logo: "/app-logos/onedrive.svg",
  },
  {
    id: "stripe",
    name: "Stripe",
    description: "Online payment processing platform",
    descriptionKey: "settings.apps.stripe.description",
    category: "payment",
    logo: "/app-logos/stripe.svg",
  },
  {
    id: "paypal",
    name: "PayPal",
    description: "Global online payment service",
    descriptionKey: "settings.apps.paypal.description",
    category: "payment",
    logo: "/app-logos/paypal.svg",
  },
  {
    id: "gmail",
    name: "Gmail",
    description: "Google email service",
    descriptionKey: "settings.apps.gmail.description",
    category: "other",
    logo: "/app-logos/gmail.svg",
  },
  {
    id: "zapier",
    name: "Zapier",
    description: "App automation and integration platform",
    descriptionKey: "settings.apps.zapier.description",
    category: "other",
    logo: "/app-logos/zapier.svg",
  },
  {
    id: "airtable",
    name: "Airtable",
    description: "Collaborative platform combining spreadsheets and databases",
    descriptionKey: "settings.apps.airtable.description",
    category: "productivity",
    logo: "/app-logos/airtable.svg",
  },
  {
    id: "clickup",
    name: "ClickUp",
    description: "All-in-one project management and productivity platform",
    descriptionKey: "settings.apps.clickup.description",
    category: "productivity",
    logo: "/app-logos/clickup.svg",
  },
  {
    id: "google-docs",
    name: "Google Docs",
    description: "Cloud document editing and collaboration tool",
    descriptionKey: "settings.apps.google_docs.description",
    category: "productivity",
    logo: "/app-logos/google-docs.svg",
  },
  {
    id: "google-sheets",
    name: "Google Sheets",
    description: "Cloud spreadsheet and data analysis tool",
    descriptionKey: "settings.apps.google_sheets.description",
    category: "productivity",
    logo: "/app-logos/google-sheets.svg",
  },
  {
    id: "outlook",
    name: "Outlook",
    description: "Microsoft email and calendar service",
    descriptionKey: "settings.apps.outlook.description",
    category: "communication",
    logo: "/app-logos/outlook.svg",
  },
  {
    id: "google-meet",
    name: "Google Meet",
    description: "Google video meeting service",
    descriptionKey: "settings.apps.google_meet.description",
    category: "communication",
    logo: "/app-logos/google-meet.svg",
  },
  {
    id: "bitbucket",
    name: "Bitbucket",
    description: "Atlassian code hosting and collaboration platform",
    descriptionKey: "settings.apps.bitbucket.description",
    category: "development",
    logo: "/app-logos/bitbucket.svg",
  },
  {
    id: "supabase",
    name: "Supabase",
    description: "Open-source Firebase alternative and backend-as-a-service",
    descriptionKey: "settings.apps.supabase.description",
    category: "development",
    logo: "/app-logos/supabase.svg",
  },
  {
    id: "zendesk",
    name: "Zendesk",
    description: "Customer service and support platform",
    descriptionKey: "settings.apps.zendesk.description",
    category: "crm",
    logo: "/app-logos/zendesk.svg",
  },
  {
    id: "figma",
    name: "Figma",
    description: "Collaborative interface design tool",
    descriptionKey: "settings.apps.figma.description",
    category: "other",
    logo: "/app-logos/figma.svg",
  },
  {
    id: "mailchimp",
    name: "Mailchimp",
    description: "Email marketing and automation platform",
    descriptionKey: "settings.apps.mailchimp.description",
    category: "other",
    logo: "/app-logos/mailchimp.svg",
  },
  {
    id: "shopify",
    name: "Shopify",
    description: "E-commerce platform and online store builder",
    descriptionKey: "settings.apps.shopify.description",
    category: "other",
    logo: "/app-logos/shopify.svg",
  },
];
